n_imgs_train: 20   #20 ori
n_imgs_val: 20     #20 ori
crop_size_train: [96, 96, 48]
crop_size_val: [96, 96, 48]
attn_heads: 2
attn_layers: 2
use_proj_occ: False

ckpt: null
seed: 0
use_amp: True

initial_epochs: 350 #350 ori
initial_lr: .001
initial_batch_size: 4

finetune_epochs: 150 #150 ori
finetune_lr: .0001
finetune_batch_size: 2

wandb_project_name: "vortx"


scannet_dir: "scannet_dir"
tsdf_dir: "scannet_dir/all_tsdf"

#scannet_dir: "../scannet_dir"
#tsdf_dir: "../scannet_dir/all_tsdf"
